### ISSUE TITLE
ask error

### ISSUE THREAD

**Issue by halobug** [danny-avila/chatgpt-clone#109]
api_1  | CLIENT RESPONSE {
api_1  |   response: 'Hello there! Did you mean to type BAAI? If so, what can I assist you with regarding that term?',
api_1  |   conversationId: '1f35b103-a084-4246-af3d-bfd71f4f81d3',
api_1  |   parentMessageId: 'd275df1b-bae1-4128-97e7-d931aa0c4177',
api_1  |   messageId: 'ae141143-74f6-4df3-b5a5-c0524ff7a529',
api_1  |   details: {}
api_1  | }
api_1  | TypeError: Cannot read properties of undefined (reading 'includes')
api_1  |     at ask (/api/server/routes/ask.js:134:25)
api_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api_1  |     at async /api/server/routes/ask.js:51:10
api_1  | The client has disconnected.

**Comment by danny-avila** [comment]
@halobug this looks like a bug from the master branch. are you on main branch?
