### ISSUE TITLE
incompatible with Docker-compose when enable host and proxy params.

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#25]
From Issue #15 

Here is the copy from @Kristovich and [his test](https://github.com/danny-avila/chatgpt-clone/issues/15#issuecomment-1464844924):

> Kristovich

> I'm using the docker compose from [da62e9a](https://github.com/danny-avila/chatgpt-clone/commit/da62e9abb37f5ff2d114621c1ebe4065295301d7). I built the api and client containers as instructed on the readme.
> 
> I also added `` console.log(`Line 11, host${host}port${port}`); `` line inside `api/server/index.js`. When `- HOST="0.0.0.0"` is set I get:
> 
> ```
> api_1      |
> api_1      | > chatgpt-clone@1.0.0 start
> api_1      | > node server/index.js
> api_1      |
> api_1      | Line 11, host"0.0.0.0"port3080
> api_1      | node:events:490
> api_1      |       throw er; // Unhandled 'error' event
> api_1      |       ^
> api_1      |
> api_1      | Error: getaddrinfo ENOTFOUND "0.0.0.0"
> api_1      |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
> api_1      | Emitted 'error' event on Server instance at:
> api_1      |     at GetAddrInfoReqWrap.doListen [as callback] (node:net:1934:12)
> api_1      |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:17) {
> api_1      |   errno: -3008,
> api_1      |   code: 'ENOTFOUND',
> api_1      |   syscall: 'getaddrinfo',
> api_1      |   hostname: '"0.0.0.0"'
> api_1      | }
> ```
> 
> If `- HOST=0.0.0.0` then
> 
> ```
> api_1      | 
> api_1      | > chatgpt-clone@1.0.0 start
> api_1      | > node server/index.js
> api_1      | 
> api_1      | Line 11, host0.0.0.0port3080
> api_1      | Server listening at http://0.0.0.0:3080
> ```
> 
> And while I'm at it: If `- PROXY=""` is present inside the docker-compose.yml, then the server will work but requests to openai or bing will fail with
> 
> ```
> api_1      | ask log {
> api_1      |   model: 'chatgpt',
> api_1      |   id: '[uuid]',
> api_1      |   sender: 'User',
> api_1      |   text: 'this is a test',
> api_1      |   parentMessageId: undefined,
> api_1      |   conversationId: undefined,
> api_1      |   chatGptLabel: '',
> api_1      |   promptPrefix: ''
> api_1      | }
> api_1      | TypeError [ERR_INVALID_URL]: Invalid URL
> api_1      |     at new NodeError (node:internal/errors:399:5)
> api_1      |     at new URL (node:internal/url:588:13)
> api_1      |     at new ProxyAgent (/api/node_modules/undici/lib/proxy-agent.js:67:25)
> api_1      |     at ChatGPTClient.getCompletion (file:///api/node_modules/@waylaidwanderer/chatgpt-api/src/ChatGPTClient.js:168:31)
> api_1      |     at ChatGPTClient.sendMessage (file:///api/node_modules/@waylaidwanderer/chatgpt-api/src/ChatGPTClient.js:297:24)
> api_1      |     at async askClient (/api/app/chatgpt-client.js:28:15)
> api_1      |     at async /api/server/routes/ask.js:90:23 {
> api_1      |   input: '""',
> api_1      |   code: 'ERR_INVALID_URL'
> api_1      | }
> ```
> 
> So I had to remove the PROXY env out of the docker-compose file for it to work.
> 
> I hope this helps.

**Comment by wtlyu** [comment]
Hi @danny-avila  and @Kristovich

 I have made some fully check of the previous pull request #19 . As motioned yesterday, it seems an incompatible issue with docker compose.

Here is my conclusion:
1. In the case of local deployment, HOST and PROXY work as expected, specific tests will be listed later
    1. Before this PR, all interface will be listen, (- although this is very insecure, any user in the LAN can access it.). I changed to listen localhost by default, and user can set `HOST=0.0.0.0` to expose to external network as before.
    2. `0.0.0.0` is not a real ip, so printing `0.0.0.0:3080` might be misleading. (actually, `localhost:3080` or `external_ip:3080` will be enabled in this case) I will start a new PR to improve this.
2. In the case of docker-compose environment, as @Kristovich said, there is error message when `- HOST="0.0.0.0"` or `- PROXY=""`
    1. It turns out a wrong usage of docker-compose, in [This](https://stackoverflow.com/questions/41988809/docker-compose-how-to-escape-environment-variables) and [This](https://github.com/docker/compose/issues/2854) .
    2. quotes shouldn't be used as `- ENV="value"`, we can use `- "ENV=value"` or `- 'ENV=value'` or `- ENV=value`.
    3. both HOST and PROXY in @Kristovich 's test are the same issue of the quotes

I have mode those tests:
```
Local environment 
test1: HOST= and no PROXY:   works on localhost
test2: HOST=localhost and no PROXY:   works localhost
test1: HOST=0.0.0.0 and no PROXY:   works all interface
test1: HOST=192.168.xx.x and no PROXY:   works on external ip
test1: HOST= and no PROXY=http://127.0.0.1:8888:   works, using proxy.


Docker environemt:
test1:
    docker compose as original: 
    works but 502. (nothing wrong. localhost in docker means not accessable outside)

test2:
    Add - HOST=0.0.0.0
    works 

test3:
    Add - HOST="0.0.0.0"
    error as @Kristovich said.  

test4:
    Add - HOST=""
    error as @Kristovich said.  

test5:
    Add - "HOST=0.0.0.0"
    works 

test6:
    Add - 'HOST=0.0.0.0'
    works 

test7:
    Add - HOST=
    works but 502, as test 1. 

test7:
    Add - PROXY=""
    error as @Kristovich said.  

test7:
    Add - PROXY=
    works
```

**Comment by wtlyu** [comment]
In short. 

That PR has no incompatible issue with docker. It's a wrong usage of docker-compose.yaml.

But I will open a new PR add this:
1. add more information on HOST=0.0.0.0, removing the misleading information
2. set env HOST=0.0.0.0 in api's Dockerfile by default. So that it won't break the README's docker demo.
3. fix the wrong example in docker-compose.yaml. This might mislead @Kristovich to write `- HOST="0.0.0.0"`:
```dockerfile
        environment:
                - PORT=3080
                - MONGO_URI=mongodb://mongodb:27017/chatgpt-clone
                - OPENAI_KEY=""        <----- WRONG, use - OPENAI_KEY=
                - CHATGPT_TOKEN=""        <----- WRONG
                - BING_TOKEN=""        <----- WRONG
```
