### ISSUE TITLE
[Bug]: TypeError: The encoded data was not valid for encoding utf-8

### ISSUE THREAD

**Issue by ostapkob** [danny-avila/chatgpt-clone#383]
### What happened?

didn't catch but backend stoped

### Relevant log output

```shell
TypeError: The encoded data was not valid for encoding utf-8
    at TextDecoder.decode (node:internal/encoding:433:16)
    at getStringFromWasm0 (/home/ggptadmin/gpt/chatgpt-clone/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:111:30)
    at module.exports.__wbindgen_error_new (/home/ggptadmin/gpt/chatgpt-clone/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:410:27)
    at wasm://wasm/00b5f812:wasm-function[59]:0x29389
    at module.exports.encoding_for_model (/home/ggptadmin/gpt/chatgpt-clone/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:177:14)
    at askClient (/home/ggptadmin/gpt/chatgpt-clone/api/app/clients/chatgpt-client.js:71:15)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ask (/home/ggptadmin/gpt/chatgpt-clone/api/server/routes/ask/askOpenAI.js:174:20)
    at async /home/ggptadmin/gpt/chatgpt-clone/api/server/routes/ask/askOpenAI.js:87:10 {
  code: 'ERR_ENCODING_INVALID_ENCODED_DATA'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
What was your input to reproduce? Did you only experience this once or is it continuing? Do you have any screenshots of the front end?

**Comment by danny-avila** [comment]
I've error handled any potential issues arising from encoding using the tokenizer. It would still be helpful if you could list steps to reproduce when you get the chance!

**Comment by ostapkob** [comment]
I deployed this service in my company and I can’t say who and what sent. But the backend crashed, after a reboot,  everything worked. If this is an archive again, I'll look at the logs.
