### ISSUE TITLE
[Bug]: When I try to run normal Bing or Sydney I get an Invalid URL error.

### ISSUE THREAD

**Issue by Kolyanpetuh** [danny-avila/chatgpt-clone#423]
### Contact Details

ons44950@gmail.com

### What happened?

I installed the program exactly as instructed and inserted a full cookie string into BINGAI_TOKEN, but I still get this error. I've tried restarting the computer and reinstalling the browser and the command line, but unfortunately none of this has helped me. At first I was getting a slightly different error, namely /turing/conversation/create: failed to parse response body.

### Steps to Reproduce

Just go to regular Bing or its hacked version (Sydney).

### Relevant log output

```shell
conversationId: '0952e7ce-51d3-40ac-bbba-f9e4379dc731'
}
bing options {
  conversationId: '0952e7ce-51d3-40ac-bbba-f9e4379dc731',
  context: null,
  systemMessage: null,
  parentMessageId: '00000000-0000-0000-0000-000000000000',
  toneStyle: 'creative',
  onProgress: [Function: wrapper]
}
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at new ProxyAgent (C:\chatgpt-clone-0.4.7\node_modules\undici\lib\proxy-agent.js:77:25)
    at BingAIClient.createNewConversation (file:///C:/chatgpt-clone-0.4.7/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:75:39)
    at BingAIClient.sendMessage (file:///C:/chatgpt-clone-0.4.7/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:184:62)
    at askBing (C:\chatgpt-clone-0.4.7\api\app\clients\bingai.js:72:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ask (C:\chatgpt-clone-0.4.7\api\server\routes\ask\askBingAI.js:137:20)
    at async C:\chatgpt-clone-0.4.7\api\server\routes\ask\askBingAI.js:75:10 {
  input: 'TRUE',
  code: 'ERR_INVALID_URL'
}
```

### Screenshots

![2023-06-03_15-53-08](https://github.com/danny-avila/chatgpt-clone/assets/87006679/dadcf4a3-2349-4804-a44b-c06a7b9db9db)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I believe this is not a bug but an IP restriction

https://github.com/waylaidwanderer/node-chatgpt-api/issues/205

So the possible solutions/workarounds are:

    set a proxy. (proxy param of BingAIClient or settings.js > bingAiClient > proxy)
    make sure your cookies are up to date. Grab them by sending a message to Bing in the browser and copying the cookies from the /turing/conversation/create network request using Dev Tools.

**Comment by danny-avila** [comment]
Actually, I was having this issue too. 

I updated to our dependency for bing's latest update

Then I needed to log into bing with edge, send a few messages, then get my full cookie string again. It's working now.

Pull the latest update for this project, made the change here: https://github.com/danny-avila/chatgpt-clone/pull/424

**Comment by Kolyanpetuh** [comment]
> Actually, I was having this issue too. 
> 
> I updated to our dependency for bing's latest update
> 
> Then I needed to log into bing with edge, send a few messages, then get my full cookie string again. It's working now.
> 
> Pull the latest update for this project, made the change here: https://github.com/danny-avila/chatgpt-clone/pull/424
> 
> I believe the headers needed to change
> 
> ![image](https://github.com/danny-avila/chatgpt-clone/assets/110412045/0f3f7c51-8950-4d98-bf77-d60f88073833)
> 

I realise that my question may be rather silly, but how can I pull this update?

**Comment by danny-avila** [comment]
No worries! Go into the directory you have the project in and open the terminal from there. Make sure the app is not running. You need git installed to do this but run the following from the directory and it will pull the latest updates. 
```
git checkout main
git pull origin main
```

**Comment by Kolyanpetuh** [comment]
> No worries! Go into the directory you have the project in and open the terminal from there. Make sure the app is not running. You need git installed to do this but run the following from the directory and it will pull the latest updates.
> 
> ```
> git checkout main
> git pull origin main
> ```
> 
> ![image](https://user-images.githubusercontent.com/110412045/243093671-b724b7f2-662a-4824-b16e-7a7c008b9912.png)
> 
> You will need to run `npm ci` again after doing this.
> 
> Or you can download the project over again however you did before, and set it up as before.

I installed git in the project directory and ran the "git checkout main" command, but I get this error: fatal: not a git repository (or any of the parent directories): .git

**Comment by Kolyanpetuh** [comment]
> No worries! Go into the directory you have the project in and open the terminal from there. Make sure the app is not running. You need git installed to do this but run the following from the directory and it will pull the latest updates. 
> ```
> git checkout main
> git pull origin main
> ```
> ![image](https://github.com/danny-avila/chatgpt-clone/assets/110412045/b724b7f2-662a-4824-b16e-7a7c008b9912)
> 
> You will need to run `npm ci` again after doing this.
> 
> Or you can download the project over again however you did before, and set it up as before.
> 

Answer me please...

**Comment by danny-avila** [comment]
How did you download the project in the first place? you may need to run `git init` then `git remote add origin https://github.com/danny-avila/chatgpt-clone.git`

as I said before, if you have issues, just download and setup as you did before

**Comment by Kolyanpetuh** [comment]
> How did you download the project in the first place? you may need to run `git init` then `git remote add origin https://github.com/danny-avila/chatgpt-clone.git`
> 
> as I said before, if you have issues, just download and setup as you did before

I could of course just reinstall the project, but I have to figure out why my git commands aren't working? Can you please help me to set up this problem? I've tried to install git to both the standard directory (C:/Program Files) and the project directory (C:/cahtgpt-clone), but nothing works in either case. I always opened the command line in the project directory. Now I get this error: Reinitialized existing Git repository in C:/chatgpt-clone-0.4.7/.git/

**Comment by danny-avila** [comment]
> Now I get this error: Reinitialized existing Git repository in C:/chatgpt-clone-0.4.7/.git/

This is not an error, this is just git telling you it already exists

Here's what you should do:

1. Open a command prompt.

2. Navigate to the directory where the project is located. For example, if the project is in a directory named `chatgpt-clone` on the `C:` drive, you would type `cd C:/chatgpt-clone`. Alternatively, open the project directory in your file explorer, right-click empty space, and select the option to open the terminal from there.

3. Run `git init`. This initializes a new Git repository in the current directory. Since the repository is already there, Git will tell you that it's reinitializing the repository, but that's okay.

4. Run `git remote add origin https://github.com/danny-avila/chatgpt-clone.git`. This sets up a link (called a "remote") between the local repository and the repository on GitHub.

5. Run `git pull origin main`. This will fetch the latest changes from the GitHub repository and merge them into the local repository.

If you're still having issues, you should start over in a different folder location with git:
`git clone https://github.com/danny-avila/chatgpt-clone.git`

**Comment by psarno** [comment]
@Kolyanpetuh If you aren't too familiar with git and you just downloaded the entire project directly as a zip (instead of cloning it), what you can do is retain a copy of your modified .env file and simply redownload the zip of the latest version and replace what you have. 

Then, take the copy of your .env file and put it back where it belongs, and delete the example one.

@danny-avila can correct me if I'm wrong here but without needing to go into the arcane magic of git command line, that shoul do the trick.

**Comment by Kolyanpetuh** [comment]
> @Kolyanpetuh If you aren't too familiar with git and you just downloaded the entire project directly as a zip (instead of cloning it), what you can do is retain a copy of your modified .env file and simply redownload the zip of the latest version and replace what you have. 
> 
> Then, take the copy of your .env file and put it back where it belongs, and delete the example one.
> 
> @danny-avila can correct me if I'm wrong here but without needing to go into the arcane magic of git command line, that shoul do the trick.

I'm not stupid about this, and I did everything right. I didn't download the project as a zip, but unzipped it to the root of my system drive. But for some reason I still get this error.

**Comment by psarno** [comment]
> I didn't download the project as a zip, but unzipped it to the root of my system drive

That would be a contradictory statement.

Did you clone it or download a zip?

**Comment by Kolyanpetuh** [comment]
> > I didn't download the project as a zip, but unzipped it to the root of my system drive
> 
> That would be a contradictory statement.
> 
> Did you clone it or download a zip?

To be honest, I don't really understand you. I downloaded the zip first and then unzipped the chatgpt-clone folder from there. I didn't create the project in zip format.

**Comment by danny-avila** [comment]
Since the main issue you brought up is resolved, I'm closing this. If you need help setting up the project further, you can open a Discussion under Troubleshooting or visit our discord server. @psarno thanks for supporting!
