### ISSUE TITLE
Application error, Trying to deploy to heroku

### ISSUE THREAD

**Issue by SethTurin** [danny-avila/chatgpt-clone#426]
Hello

I'm trying to deploy to heroku, but running into issues. 

I've gone through all the steps in the walkthrough, and looked through the suggestions here: https://github.com/danny-avila/chatgpt-clone/discussions/339

here is my log:
`2023-06-03T20:15:18.615499+00:00 app[web.1]: > chat-backend@0.4.7 start
2023-06-03T20:15:18.615502+00:00 app[web.1]: > node server/index.js
2023-06-03T20:15:18.615503+00:00 app[web.1]:
2023-06-03T20:15:19.970796+00:00 app[web.1]: Connected to MongoDB
2023-06-03T20:15:20.028687+00:00 app[web.1]: [Migrate] Nothing to migrate
2023-06-03T20:15:20.030702+00:00 app[web.1]: Error: Meilisearch not configured, search will be disabled.
2023-06-03T20:15:20.030702+00:00 app[web.1]: at indexSync (/app/api/lib/db/indexSync.js:11:13)
2023-06-03T20:15:20.030704+00:00 app[web.1]: at /app/api/server/index.js:19:9
2023-06-03T20:15:20.030705+00:00 app[web.1]: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-06-03T20:15:20.036385+00:00 app[web.1]: There was an uncaught error: JwtStrategy requires a secret or key
2023-06-03T20:15:20.036520+00:00 app[web.1]: Clearing sync timeouts before exiting...
2023-06-03T20:15:20.046856+00:00 app[web.1]: npm notice
2023-06-03T20:15:20.047113+00:00 app[web.1]: npm notice New minor version of npm available! 9.5.1 -> 9.6.7
2023-06-03T20:15:20.047177+00:00 app[web.1]: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.7>
2023-06-03T20:15:20.047282+00:00 app[web.1]: npm notice Run `npm install -g npm@9.6.7` to update!
2023-06-03T20:15:20.047330+00:00 app[web.1]: npm notice
2023-06-03T20:15:20.201245+00:00 heroku[web.1]: Process exited with status 1
2023-06-03T20:15:20.227207+00:00 heroku[web.1]: State changed from starting to crashed
2023-06-03T20:15:21.575489+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=smart-agent.herokuapp.com request_id=1ee38d60-fb77-4d97-bddd-1cab48656226 fwd="71.126.181.76" dyno= connect= service= status=503 bytes= protocol=https
2023-06-03T20:15:22.095038+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=smart-agent.herokuapp.com request_id=08582cf6-d93a-41a1-ac9c-3fb28cf62712 fwd="71.126.181.76" dyno= connect= service= status=503 bytes= protocol=https`

Is there anything I might be missing?
Thanks

**Comment by SethTurin** [comment]
Update: The previous error is solved by setting the JWT_SECRET_PROD environment variable, like so
`heroku config:set JWT_SECRET_PROD=secret --app your-app-name`

Now I'm seeing a different issue:

`2023-06-03T20:33:33.953290+00:00 app[web.1]: Connected to MongoDB
2023-06-03T20:33:34.028724+00:00 app[web.1]: [Migrate] Nothing to migrate
2023-06-03T20:33:34.030100+00:00 app[web.1]: Error: Meilisearch not configured, search will be disabled.
2023-06-03T20:33:34.030101+00:00 app[web.1]: at indexSync (/app/api/lib/db/indexSync.js:11:13)
2023-06-03T20:33:34.030101+00:00 app[web.1]: at /app/api/server/index.js:19:9
2023-06-03T20:33:34.030102+00:00 app[web.1]: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-06-03T20:33:34.035659+00:00 app[web.1]: Server listening at http://localhost:35485
2023-06-03T20:34:31.077055+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2023-06-03T20:34:31.093954+00:00 heroku[web.1]: Stopping process with SIGKILL
2023-06-03T20:34:31.108168+00:00 app[web.1]: Error waiting for process to terminate: No child processes
2023-06-03T20:34:31.267490+00:00 heroku[web.1]: Process exited with status 22
2023-06-03T20:34:31.297038+00:00 heroku[web.1]: State changed from starting to crashed
2023-06-03T20:34:34.306130+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=smart-agent.herokuapp.com request_id=68e770da-8472-4160-a2e6-f7f9c13b3a4b fwd="71.126.181.76" dyno= connect= service= status=503 bytes= protocol=https
2023-06-03T20:34:34.805597+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=smart-agent.herokuapp.com request_id=c5903448-fa06-4467-8b54-74d31d3b05f3 fwd="71.126.181.76" dyno= connect= service= status=503 bytes= protocol=https

Please assist.

**Comment by danny-avila** [comment]
I haven’t deployed on heroku but a quick google search got me this

https://stackoverflow.com/questions/15693192/heroku-node-js-error-web-process-failed-to-bind-to-port-within-60-seconds-of


There are several alternative solutions proposed. 

The relevant code you will need to change is here: 
api/server/index.js

**Comment by SethTurin** [comment]
I did manage to fix this and the solution, IIRC, was to set the port as an environment variable. I did it like this: `heroku config:set HOST=0.0.0.0 --app my-app`

Most of the problems I've run into have been fixed by adding more environment variables.

**Comment by danny-avila** [comment]
Nice, glad it's working for you! Heroku is particular with its bindings
