### ISSUE TITLE
Uncaught Error: `props.dangerouslySetInnerHTML` must be in the form `{__html: ...}`. 

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#53]
example question: 如何在react中使用contenteditable

```
Uncaught Error: `props.dangerouslySetInnerHTML` must be in the form `{__html: ...}`. Please visit https://reactjs.org/link/dangerously-set-inner-html for more information.
    at assertValidProps (react-dom.development.js:2952:1)
    at setInitialProperties (react-dom.development.js:9920:1)
    at finalizeInitialChildren (react-dom.development.js:10950:1)
    at completeWork (react-dom.development.js:22193:1)
    at completeUnitOfWork (react-dom.development.js:26596:1)
    at performUnitOfWork (react-dom.development.js:26568:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performSyncWorkOnRoot (react-dom.development.js:26096:1)
assertValidProps @ react-dom.development.js:2952
setInitialProperties @ react-dom.development.js:9920
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performSyncWorkOnRoot @ react-dom.development.js:26096
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
XMLHttpRequest.send (async)
SSE.stream @ sse.js:200
(anonymous) @ TextChat.jsx:222
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
```

**Comment by danny-avila** [comment]
This should be a simple fix to escape any html/jsx the AI generates

**Comment by danny-avila** [comment]
Looks like I may have no action here, haven't gotten this issue in a while either.

This is partly due to the way highlight.js is used with React: https://github.com/highlightjs/highlight.js/issues/925

As you can see there, the dangerouslySetInnerHTML is used in almost all cases

This stackoverflow makes the distinction why: https://stackoverflow.com/questions/37337289/react-js-set-innerhtml-vs-dangerouslysetinnerhtml

lastly, this comment mentions h.js escapes the necessary characters for an attack under the hood: https://github.com/highlightjs/highlight.js/issues/2537#issuecomment-626319162

It's worth mentioning the official site uses h.js, too
